apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app-5
  description: Python app displays the time and named python-app-5.
  annotations:
    github.com/project-slug: ruben-pinzon/python-app-5
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development

  lifecycle: experimental

